function vending_machine_simulation()
    % Vending machine start screen
    machine_fig = figure('Name', 'Vending Machine', 'Position', [100, 100, 1000, 800], ...
                         'Color', [1, 1, 1]);

    % Vending machine image
    axes('Position', [0.1, 0.2, 0.8, 0.6]);
    try
        imshow('VendingMachine.png'); % Main vending machine image
    catch
        warning('Vending machine image could not be loaded!');
        text(0.5, 0.5, 'Vending Machine Image Missing', 'HorizontalAlignment', 'center', ...
             'FontSize', 16, 'FontWeight', 'bold', 'Color', [1, 0, 0]);
    end
    axis off;

    % Next button
    uicontrol(machine_fig, 'Style', 'pushbutton', ...
              'Position', [450, 50, 100, 40], ...
              'String', 'Next', ...
              'FontSize', 12, ...
              'Callback', @go_to_selection_screen);
end

function go_to_selection_screen(~, ~)
    % Product selection screen
    selection_fig = figure('Name', 'Product Selection', 'Position', [100, 100, 1000, 800], ...
                           'Color', [1, 1, 1]);

    % Product details
    products = {'Ice Cream', 'Croissant', 'Chocolate', 'Popcorn', 'Chips', 'Macarons', ...
                'Apple Juice', 'Milk', 'Soda'};
    prices = [5.00, 4.50, 6.00, 3.00, 3.50, 7.00, 4.00, 3.00, 2.50];
    images = {'IceCream.png', 'Croissant.png', 'Chocolate.png', 'Popcorn.png', 'Chips.png', ...
              'Macarons.png', 'AppleJuice.png', 'Milk.png', 'Soda.png'};

    % Selected products and total price
    selectedProducts = {};
    totalPrice = 0;

    % Selected products and total price display
    uicontrol(selection_fig, 'Style', 'text', ...
              'Position', [750, 700, 200, 30], ...
              'String', 'Selected Products:', ...
              'FontSize', 12, ...
              'HorizontalAlignment', 'left', ...
              'BackgroundColor', [1, 1, 1]);

    selectedList = uicontrol(selection_fig, 'Style', 'listbox', ...
                             'Position', [750, 450, 200, 200], ...
                             'String', selectedProducts);

    % Total price display
    totalText = uicontrol(selection_fig, 'Style', 'text', ...
                          'Position', [750, 400, 200, 30], ...
                          'String', sprintf('Total: %.2f €', totalPrice), ...
                          'FontSize', 12, ...
                          'BackgroundColor', [1, 1, 1]);

    % Pay button
    uicontrol(selection_fig, 'Style', 'pushbutton', ...
              'Position', [750, 350, 200, 40], ...
              'String', 'Pay', ...
              'FontSize', 12, ...
              'Callback', @(src, event) go_to_payment_screen(selectedProducts, totalPrice));

    % Product grid
    cols = 4;
    rows = ceil(length(products) / cols);
    spacing_x = 200;
    spacing_y = 250;
    start_x = 50;
    start_y = 650;

    for i = 1:length(products)
        col = mod(i-1, cols);
        row = floor((i-1) / cols);

        % Product image
        axes('Units', 'pixels', 'Position', [start_x + col * spacing_x, start_y - row * spacing_y, 120, 120]);
        try
            imshow(images{i});
        catch
            warning('Image missing: %s', images{i});
            rectangle('Position', [0, 0, 1, 1], 'FaceColor', [0.8, 0.8, 0.8]);
            text(0.5, 0.5, 'Image Missing', 'HorizontalAlignment', 'center', ...
                 'FontSize', 10, 'FontWeight', 'bold', 'Color', [1, 0, 0]);
        end
        axis off;

        % Product name
        uicontrol(selection_fig, 'Style', 'text', ...
                  'Position', [start_x + col * spacing_x, start_y - row * spacing_y - 30, 120, 20], ...
                  'String', lower(products{i}), ...
                  'FontSize', 12, ...
                  'FontWeight', 'bold', ...
                  'HorizontalAlignment', 'center', ...
                  'BackgroundColor', [1, 1, 1]);

        % Product price
        uicontrol(selection_fig, 'Style', 'text', ...
                  'Position', [start_x + col * spacing_x, start_y - row * spacing_y - 60, 120, 20], ...
                  'String', sprintf('%.2f €', prices(i)), ...
                  'FontSize', 10, ...
                  'HorizontalAlignment', 'center', ...
                  'BackgroundColor', [1, 1, 1]);

        % Select button
        uicontrol(selection_fig, 'Style', 'pushbutton', ...
                  'Position', [start_x + col * spacing_x, start_y - row * spacing_y - 90, 120, 30], ...
                  'String', 'Select', ...
                  'Callback', @(src, event) selectProduct(products{i}, prices(i)));
    end

    % Product selection callback
    function selectProduct(product, price)
        selectedProducts{end+1} = product; %#ok<AGROW>
        totalPrice = totalPrice + price;
        set(selectedList, 'String', selectedProducts);
        set(totalText, 'String', sprintf('Total: %.2f €', totalPrice));
    end
end

function go_to_payment_screen(selected_products, total_price)
    % Payment screen
    payment_fig = figure('Name', 'Payment Screen', 'Position', [100, 100, 1200, 800], ...
                         'Color', [0.95, 0.95, 0.95]); % Light gray background

    % Header
    uicontrol(payment_fig, 'Style', 'text', ...
              'Position', [450, 750, 300, 40], ...
              'String', 'Payment Screen', ...
              'FontSize', 16, ...
              'FontWeight', 'bold', ...
              'HorizontalAlignment', 'center', ...
              'BackgroundColor', [0.95, 0.95, 0.95]);

    % Selected Products Header
    uicontrol(payment_fig, 'Style', 'text', ...
              'Position', [50, 700, 300, 30], ...
              'String', 'Selected Products:', ...
              'FontSize', 14, ...
              'FontWeight', 'bold', ...
              'HorizontalAlignment', 'left', ...
              'BackgroundColor', [0.95, 0.95, 0.95]);

    % Selected Products Table
    product_table = uitable(payment_fig, 'Data', [selected_products', num2cell(total_price / length(selected_products))'], ...
                            'ColumnName', {'Product', 'Price (€)'}, ...
                            'Position', [50, 450, 300, 200]);

    % Total Price
    uicontrol(payment_fig, 'Style', 'text', ...
              'Position', [50, 400, 300, 30], ...
              'String', sprintf('Total Price: %.2f €', total_price), ...
              'FontSize', 14, ...
              'FontWeight', 'bold', ...
              'HorizontalAlignment', 'left', ...
              'BackgroundColor', [0.95, 0.95, 0.95]);

    % Total Paid
    total_paid = 0;
    total_paid_display = uicontrol(payment_fig, 'Style', 'text', ...
                                   'Position', [50, 370, 300, 30], ...
                                   'String', sprintf('Total Paid: %.2f €', total_paid), ...
                                   'FontSize', 14, ...
                                   'FontWeight', 'bold', ...
                                   'HorizontalAlignment', 'left', ...
                                   'BackgroundColor', [0.95, 0.95, 0.95]);

    % Remaining Amount
    remaining_display = uicontrol(payment_fig, 'Style', 'text', ...
                                  'Position', [50, 340, 300, 30], ...
                                  'String', sprintf('Remaining: %.2f €', total_price - total_paid), ...
                                  'FontSize', 14, ...
                                  'FontWeight', 'bold', ...
                                  'ForegroundColor', [1, 0, 0], ...
                                  'HorizontalAlignment', 'left', ...
                                  'BackgroundColor', [0.95, 0.95, 0.95]);

    % Payment Options
    euro_values = [0.01, 0.02, 0.05, 0.10, 0.20, 0.50, 1, 2, 10, 20, 50];
    euro_images = {'1Cent.png', '2Cent.png', '5Cent.png', '10Cent.png', '20Cent.png', ...
                   '50Cent.png', '1Euro.png', '2Euro.png', '10Euro.png', '20Euro.png', '50Euro.png'};

    cols = 5;
    spacing_x = 200;
    spacing_y = 150;
    start_x = 400;
    start_y = 550;

    for i = 1:length(euro_values)
        col = mod(i-1, cols);
        row = floor((i-1) / cols);

        % Coin/Note Image
        axes('Units', 'pixels', 'Position', [start_x + col * spacing_x, start_y - row * spacing_y + 50, 50, 50]);
        try
            imshow(euro_images{i});
        catch
            rectangle('Position', [0, 0, 1, 1], 'FaceColor', [0.8, 0.8, 0.8]);
            text(0.5, 0.5, '?', 'HorizontalAlignment', 'center', 'FontSize', 20, 'Color', [1, 0, 0]);
        end
        axis off;

        % Coin/Note Button
        uicontrol(payment_fig, 'Style', 'pushbutton', ...
                  'Position', [start_x + col * spacing_x, start_y - row * spacing_y, 100, 30], ...
                  'String', sprintf('%.2f €', euro_values(i)), ...
                  'Callback', @(src, event) add_money(euro_values(i), total_paid_display, remaining_display, total_price));
    end

    % Finalize Payment Button
    finalize_btn = uicontrol(payment_fig, 'Style', 'pushbutton', ...
                             'Position', [900, 50, 200, 50], ...
                             'String', 'Finalize Payment', ...
                             'FontSize', 14, ...
                             'FontWeight', 'bold', ...
                             'BackgroundColor', [0.5, 0.5, 0.5], ...
                             'ForegroundColor', [1, 1, 1], ...
                             'Enable', 'off', ...
                             'Callback', @(src, event) finalize_payment(total_price, total_paid));

    % Add Money Callback
    function add_money(amount, total_paid_display, remaining_display, total_price)
        total_paid = total_paid + amount;
        set(total_paid_display, 'String', sprintf('Total Paid: %.2f €', total_paid));
        remaining = total_price - total_paid;
        set(remaining_display, 'String', sprintf('Remaining: %.2f €', max(0, remaining)));
        if remaining <= 0
            set(finalize_btn, 'BackgroundColor', [0.2, 0.6, 1], 'Enable', 'on');
        end
    end

    % Finalize Payment Callback
    function finalize_payment(total_price, total_paid)
        if total_paid < total_price
            msgbox(sprintf('Insufficient Payment! Remaining: %.2f €', total_price - total_paid), 'Error', 'error');
        else
            change = total_paid - total_price;
            if change > 0
                msgbox(sprintf('Payment Completed! Change: %.2f €', change), 'Success');
            else
                msgbox('Payment Completed! No Change Required.', 'Success');
            end
            close(payment_fig); % Close the payment screen
        end
    end
end
